version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/foodgram_backend/
    env_file: .env
    volumes:
      - media:/media
      - static:/backend_static


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./frontend/:/app/result_build/


  gateway:
    build: ./gateway/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
