version: '3.3'

volumes:
  pg_data:
  static:
  media:
  static_frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: dodonova/foodgram_backend
    env_file: .env
    volumes:
      - media:/media
      - static:/app/static_django/
    depends_on:
      - db

  frontend:
    image: dodonova/foodgram_frontend
    volumes:
      - static_frontend:/app/result_build/
  
  gateway:
    image: dodonova/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ../gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static_django/
      - media:/media/
      - static_frontend:/static_frontend/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
