# Generated by Django 3.2.3 on 2023-12-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': ('избранное',), 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': ('единица измерения',), 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': ('рецепт',), 'verbose_name_plural': 'Рецепты'},
        ),
    ]
