# Generated by Django 3.2.3 on 2023-12-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='measurement_unit',
        ),
    ]
