# Generated by Django 3.2.3 on 2023-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipeingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(related_name='tags', through='recipes.RecipeTag', to='recipes.Tag', verbose_name='Tag'),
        ),
    ]
