# Generated by Django 3.2.3 on 2023-12-02 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20231202_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_measurement_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='recipes.measurement', verbose_name='ед.измерения'),
        ),
    ]
