# Generated by Django 3.2.3 on 2023-12-02 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement',
            new_name='MeasurementUnit',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='measurement',
            new_name='measurement_unit',
        ),
    ]
