# Generated by Django 3.2.3 on 2023-12-27 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipe_ingredients', to='recipes.measurementunit', verbose_name='ед. измерения'),
        ),
    ]
