# Generated by Django 3.2.3 on 2024-01-27 16:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingList',
            new_name='ShoppingCart',
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': ('shopping list',), 'verbose_name_plural': 'Shopping Lists'},
        ),
    ]
