# Generated by Django 3.2.3 on 2024-01-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipeingredient_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementunit',
            options={'ordering': ('name',), 'verbose_name': ('ед. измерения',), 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': ('рецепт',), 'verbose_name_plural': 'Рецепты'},
        ),
    ]
